<?xml version="1.0"?>
<robot name="edumip_my_robot"  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="wheel_separation" value="0.070" /> 
  <xacro:property name="wheel_radius"     value="0.034" /> 
  <xacro:property name="wheel_width"      value="0.010" />
  <xacro:property name="body_height"      value="0.1"   /> 
  <xacro:property name="body_width"       value="0.050" /> 
  <xacro:property name="body_length"      value="0.035" />
  <xacro:property name="pii"              value="3.1415"/>
  <xacro:property name="camera_link"      value="0.025" />

  <material name="red">
    <color rgba="0.8 0 0 .5"/>
  </material>

  <material name="green">
    <color rgba="0 0.8 0 .5"/>
  </material>

  <material name="blue">
    <color rgba="0 0 0.8 .5"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 .5"/>
  </material>

  <link name="edumip_body">
    <visual>
      <origin xyz="0 0 ${0.5*body_height}" rpy="0 -0.20 0"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
  

   <collision>
      <origin xyz="0 0 ${0.5*body_height}" rpy="0 -0.20 0"/>      
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>	
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 -.5" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
    </inertial>

  </link>

  <link name="wheelL">
    <visual>
      <origin rpy="${pii/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="${pii/2} 0  0" />
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="1" iyz="0" izz="0.1"/>
    </inertial>

  </link>

    

  <joint name="jointL" type="continuous">
    <axis xyz="0 1 0" rpy="0 0 0" />
    <parent link="edumip_body"/>
    <child link="wheelL"/>
    <origin rpy="0 0 0" xyz="0 ${wheel_separation * 0.5} 0.0"/>
  </joint>

  <link name="wheelR">
    <visual>
      <origin rpy="${pii/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="${pii/2} 0  0" />
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="1" iyz="0" izz="0.1"/>
    </inertial>

  </link>

    

  <joint name="jointR" type="continuous">
    <axis xyz="0 1 0" rpy="0 0 0" />
    <parent link="edumip_body"/>
    <child link="wheelR"/>
    <origin rpy="0 0 0" xyz="0 ${-wheel_separation * 0.5} 0.0"/>
  </joint>

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 ${body_height+(.3*camera_link)}" rpy="0 .1 0"/>
    <parent link="edumip_body"/>
    <child link="camera_link"/>
  </joint>

  <!-- Camera -->
  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <gazebo reference="camera_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="edumip_body">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <material>Gazebo/Blue</material>
  </gazebo>

  <gazebo reference="wheelR">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="wheelL">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="stripeL">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <material>Gazebo/Blue</material>
  </gazebo>

  <gazebo reference="mass">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <material>Gazebo/Black</material>
  </gazebo>

<gazebo>
 <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
   <legacyMode>false</legacyMode>
   <rosDebugLevel>3</rosDebugLevel>
   <alwaysOn>true</alwaysOn>
   <updateRate>10</updateRate>
   <leftJoint>jointL</leftJoint>
   <rightJoint>jointR</rightJoint>
   <wheelSeparation>${wheel_separation}</wheelSeparation>
   <wheelDiameter>${wheel_radius*2.0}</wheelDiameter>
   <torque>0.1</torque>
   <commandTopic>/edumip/cmd</commandTopic>
   <odometryTopic>/edumip/odom</odometryTopic>
   <odometryFrame>world</odometryFrame>
   <robotBaseFrame>edumip_body</robotBaseFrame>
   <publishTf>1</publishTf> 
   <publishWheelTF>false</publishWheelTF> 
   <publishWheelJointState>true</publishWheelJointState>  
   <wheelAcceleration>0</wheelAcceleration>
   <wheelTorque>0.1</wheelTorque>
   <odometrySource>world</odometrySource>
 </plugin>
</gazebo>

<gazebo reference="camera_link">
 <sensor type="camera" name="camera1">
   <update_rate>30.0</update_rate>
   <camera name="head">
     <horizontal_fov>1.3962634</horizontal_fov>
     <image>
       <width>800</width>
       <height>800</height>
       <format>R8G8B8</format>
     </image>
     <clip>
       <near>0.02</near>
       <far>300</far>
     </clip>
     <noise>
       <type>gaussian</type>
       <mean>0.0</mean>
       <stddev>0.007</stddev>
     </noise>
   </camera>
   <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
     <robotNamespace>edumip</robotNamespace>
     <alwaysOn>true</alwaysOn>
     <updateRate>10.0</updateRate>
     <cameraName>camera1</cameraName>
     <imageTopicName>image_raw</imageTopicName>
     <cameraInfoTopicName>camera_info</cameraInfoTopicName>
     <frameName>camera_link</frameName>
     <hackBaseline>0.07</hackBaseline>
     <distortionK1>0.0</distortionK1>
     <distortionK2>0.0</distortionK2>
     <distortionK3>0.0</distortionK3>
     <distortionT1>0.0</distortionT1>
     <distortionT2>0.0</distortionT2>
   </plugin>
 </sensor>
</gazebo>


</robot>
